<?
$arUrlRewrite = array(
    array(
        "CONDITION" => "#^/collective/kontsertnyy-orkestr-yugry/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/kontsertnyy-orkestr-yugry/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/kontsertnyy-orkestr-yugry/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/kontsertnyy-orkestr-yugry/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/kontsertnyy-orkestr-yugry/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/kontsertnyy-orkestr-yugry/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/kontsertnyy-orkestr-yugry/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/kontsertnyy-orkestr-yugry/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/kontsertnyy-orkestr-yugry/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/kontsertnyy-orkestr-yugry/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/kontsertnyy-orkestr-yugry/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/kontsertnyy-orkestr-yugry/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/ans-pes-i-tants/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/ans-pes-i-tants/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/ans-pes-i-tants/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/ans-pes-i-tants/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/ans-pes-i-tants/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/ans-pes-i-tants/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/solisty-yugry/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/solisty-yugry/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/dukh-or-yugry/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/dukh-or-yugry/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/solisty-yugry/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/solisty-yugry/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/ans-pes-i-tants/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/ans-pes-i-tants/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/akadem-tants/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/akadem-tants/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/dukh-or-yugry/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/dukh-or-yugry/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/solisty-yugry/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/solisty-yugry/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/dukh-or-yugry/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/dukh-or-yugry/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/sibir-brass/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/sibir-brass/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/akadem-tants/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/akadem-tants/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/akadem-tants/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/akadem-tants/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/sibir-brass/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/sibir-brass/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/solisty-yugry/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/solisty-yugry/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/dukh-or-yugry/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/dukh-or-yugry/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/sibir-brass/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/sibir-brass/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/teatr-kost/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/teatr-kost/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/akadem-tants/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/akadem-tants/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/teatr-kost/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/teatr-kost/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/teatr-kost/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/teatr-kost/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/sibir-brass/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/sibir-brass/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/ans-pes-i-tants/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/ans-pes-i-tants/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/konsone/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/konsone/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/teatr-kost/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/teatr-kost/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/konsone/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/konsone/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/konsone/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/konsone/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/smola/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/smola/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/solisty-yugry/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/solisty-yugry/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/сollective/mlada/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/сollective/mlada/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/dukh-or-yugry/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/dukh-or-yugry/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/mlada/o-nas/photogal/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/mlada/o-nas/photogal/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/ans-pes-i-tants/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/ans-pes-i-tants/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/smola/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/smola/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/mlada/o-nas/artisty/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/mlada/o-nas/artisty/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/smola/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/smola/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/akadem-tants/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/akadem-tants/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/mlada/o-nas/control/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/mlada/o-nas/control/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/konsone/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/konsone/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/dukh-or-yugry/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/dukh-or-yugry/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/solisty-yugry/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/solisty-yugry/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/sibir-brass/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/sibir-brass/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/mlada/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/mlada/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/smola/o-nas/video/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/smola/o-nas/video/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/akadem-tants/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/akadem-tants/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/teatr-kost/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/teatr-kost/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/sibir-brass/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/sibir-brass/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/teatr-kost/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/teatr-kost/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/konsone/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/konsone/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/konsone/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/konsone/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/mlada/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/mlada/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/bitrix/services/ymarket/#",
        "RULE" => "",
        "ID" => "",
        "PATH" => "/bitrix/services/ymarket/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/smola/afisha/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/smola/afisha/index.php",
    ),
    array(
        "CONDITION" => "#^/events/official_events/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/events/official_events/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/smola/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/smola/news/index.php",
    ),
    array(
        "CONDITION" => "#^/collective/mlada/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/collective/mlada/news/index.php",
    ),
    array(
        "CONDITION" => "#^/сollective/mlada/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/сollective/mlada/news/index.php",
    ),
    array(
        "CONDITION" => "#^/news/newsculture/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/news/newsculture/index.php",
    ),
    array(
        "CONDITION" => "#^/news/backstage/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/news/backstage/index.php",
    ),
    array(
        "CONDITION" => "#^/collective2/#",
        "RULE" => "",
        "ID" => "ugraweb:collective",
        "PATH" => "/collective2/index.php",
    ),
    array(
        "CONDITION" => "#^/news/photo/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/news/photo/index.php",
    ),
    array(
        "CONDITION" => "#^/events/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/events/index.php",
    ),
    array(
        "CONDITION" => "#^/news/#",
        "RULE" => "",
        "ID" => "bitrix:news",
        "PATH" => "/news/index.php",
    ),
);

?>